server:
  port: 7979
  servlet:
    context-path: /watch_store

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/watch_store"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "S8dZU9pf2mqiMHkXmSshryCqL1yMMKBq2s7Mv8w2n6Rct8Jr7GkTwzi38VPWsCgw"